"""ilk sema: 12 tablo (Bolum 5)

Revision ID: 45062fb8e787
Revises: 
Create Date: 2026-09-18 20:56:28.015019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45062fb8e787'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('symbols_succeeded', sa.Integer(), nullable=False),
    sa.Column('symbols_failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name='ck_calculation_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_source_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('healthy', 'degraded', 'down')", name='ck_data_source_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_data_source_status_source_time', 'data_source_status', ['source_name', sa.text('checked_at DESC')], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('has_options_data', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_index('idx_symbols_active', 'symbols', ['is_active'], unique=False, postgresql_where=sa.text('is_active IS true'))
    op.create_index('idx_symbols_ticker', 'symbols', ['ticker'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('theme_preference', sa.String(length=10), nullable=False),
    sa.Column('density_preference', sa.String(length=10), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("density_preference IN ('standard', 'compact')", name='ck_users_density'),
    sa.CheckConstraint("theme_preference IN ('dark', 'light', 'system')", name='ck_users_theme'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('condition_type', sa.String(length=30), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('channels', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("condition_type IN ('flip_distance', 'regime_change', 'gex_pct_change', 'price_level')", name='ck_alerts_condition_type'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_enabled_symbol', 'alerts', ['symbol_id'], unique=False, postgresql_where=sa.text('enabled IS true'))
    op.create_index('idx_alerts_user', 'alerts', ['user_id'], unique=False)
    op.create_table('gex_by_strike',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('call_gex', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('put_gex', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('net_gex', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('calculation_run_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gex_by_strike_symbol_run', 'gex_by_strike', ['symbol_id', 'calculation_run_id'], unique=False)
    op.create_index('idx_gex_by_strike_symbol_time', 'gex_by_strike', ['symbol_id', sa.text('computed_at DESC')], unique=False)
    op.create_table('gex_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('total_net_gex', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('gamma_flip_strike', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('call_wall_strike', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('put_wall_strike', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('regime', sa.String(length=10), nullable=False),
    sa.Column('spot_price_at_calc', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('calculation_run_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("regime IN ('positive', 'negative', 'neutral', 'unknown')", name='ck_gex_summary_regime'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gex_summary_symbol_time', 'gex_summary', ['symbol_id', sa.text('computed_at DESC')], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_journal_symbol', 'journal_entries', ['symbol_id'], unique=False, postgresql_where=sa.text('symbol_id IS NOT NULL'))
    op.create_index('idx_journal_user_time', 'journal_entries', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_table('option_chain_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('call_oi', sa.Integer(), nullable=False),
    sa.Column('put_oi', sa.Integer(), nullable=False),
    sa.Column('call_gamma', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('put_gamma', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('call_iv', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('put_iv', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_option_chain_symbol_strike_expiry', 'option_chain_raw', ['symbol_id', 'strike', 'expiry'], unique=False)
    op.create_index('idx_option_chain_symbol_time', 'option_chain_raw', ['symbol_id', sa.text('fetched_at DESC')], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('spot_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('daily_change_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_snapshots_symbol_time', 'price_snapshots', ['symbol_id', sa.text('fetched_at DESC')], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol_id', name='uq_watchlist_user_symbol')
    )
    op.create_index('idx_watchlist_user', 'watchlist_items', ['user_id', 'sort_order'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_symbol_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_symbol_id'], ['symbols.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notifications_user_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_watchlist_user', table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index('idx_price_snapshots_symbol_time', table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index('idx_option_chain_symbol_time', table_name='option_chain_raw')
    op.drop_index('idx_option_chain_symbol_strike_expiry', table_name='option_chain_raw')
    op.drop_table('option_chain_raw')
    op.drop_index('idx_journal_user_time', table_name='journal_entries')
    op.drop_index('idx_journal_symbol', table_name='journal_entries', postgresql_where=sa.text('symbol_id IS NOT NULL'))
    op.drop_table('journal_entries')
    op.drop_index('idx_gex_summary_symbol_time', table_name='gex_summary')
    op.drop_table('gex_summary')
    op.drop_index('idx_gex_by_strike_symbol_time', table_name='gex_by_strike')
    op.drop_index('idx_gex_by_strike_symbol_run', table_name='gex_by_strike')
    op.drop_table('gex_by_strike')
    op.drop_index('idx_alerts_user', table_name='alerts')
    op.drop_index('idx_alerts_enabled_symbol', table_name='alerts', postgresql_where=sa.text('enabled IS true'))
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_symbols_ticker', table_name='symbols')
    op.drop_index('idx_symbols_active', table_name='symbols', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('symbols')
    op.drop_index('idx_data_source_status_source_time', table_name='data_source_status')
    op.drop_table('data_source_status')
    op.drop_table('calculation_runs')
    # ### end Alembic commands ###
