"""IV sutunlarini genislet (asiri saglayici degerleri)

Revision ID: d10a4fdd02a5
Revises: f973b1f3ceca
Create Date: 2026-09-18 22:39:32.538884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10a4fdd02a5'
down_revision: Union[str, None] = 'f973b1f3ceca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('option_chain_raw', 'call_iv',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=True)
    op.alter_column('option_chain_raw', 'put_iv',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('option_chain_raw', 'put_iv',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.NUMERIC(precision=8, scale=6),
               existing_nullable=True)
    op.alter_column('option_chain_raw', 'call_iv',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.NUMERIC(precision=8, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###
