"""symbols.indices alani (endeks uyeligi)

Revision ID: f973b1f3ceca
Revises: 45062fb8e787
Create Date: 2026-09-18 22:20:51.809221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f973b1f3ceca'
down_revision: Union[str, None] = '45062fb8e787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbols', sa.Column('indices', sa.String(length=20), nullable=True))
    op.create_index('idx_symbols_indices', 'symbols', ['indices'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_symbols_indices', table_name='symbols')
    op.drop_column('symbols', 'indices')
    # ### end Alembic commands ###
